version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port for messaging
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db-orders:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  orders-api:
    image: lucasgoleiro/techchallenge-orders-api
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - db-orders

  db-customers:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
  customers-api:
    image: lucasgoleiro/techchallenge-customers-api
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
      - db-customers

  db-products:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres
  products-api:
    image: lucasgoleiro/techchallenge-products-api
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
      - db-products  

  db-payment:
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: postgres
  payment-api:
    image: lucasgoleiro/techchallenge-payment-api
    ports:
      - 8083:8083
    depends_on:
      - rabbitmq
      - db-payment   

  db-kitchen:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
  kitchen-api:
    image: lucasgoleiro/techchallenge-kitchen-api
    ports:
      - 8084:8084
    depends_on:
      - rabbitmq
      - db-kitchen  